name: location_brazil
description: App to locate the city in Brazil you are.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_geopackage: ^0.4.8
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.2
  location: ^4.3.0
  bloc: ^7.0.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.10

flutter_icons:
  android: true
  image_path: "assets/icon/br.png"

flutter:
  uses-material-design: true
  assets:
    - geodatabase/BR_Municipios_2019.gpkg
    - assets/icon/br.png
    - assets/translations/